In [1]:
Tp = {
    'Sunny': {'Sunny': 0.7, 'Rainy': 0.3},  # Probabilities from Sunny
    'Rainy': {'Sunny': 0.5, 'Rainy': 0.5}   # Probabilities from Rainy
}

Ep = {
    'Sunny': {'Walk': 0.6, 'Shop': 0.1, 'Clean': 0.3},  # Probabilities of observations from Sunny
    'Rainy': {'Walk': 0.1, 'Shop': 0.7, 'Clean': 0.2}   # Probabilities of observations from Rainy
}

observations = ['Clean', 'Shop','Walk']

Initial_prob = [1, 0]

In [2]:
import numpy as np

In [3]:
#FORWARD PROCEDURE

alpha = np.zeros((len(Tp), len(observations)+1))
alpha[:,0] = Initial_prob

for i in range(1, len(observations)+1):
  alpha[0][i] = alpha[0][i-1]*Tp['Sunny']['Sunny']*Ep['Sunny'][observations[i-1]] + alpha[1][i-1]*Tp['Rainy']['Sunny']*Ep['Rainy'][observations[i-1]]
  alpha[1][i] = alpha[1][i-1]*Tp['Rainy']['Rainy']*Ep['Rainy'][observations[i-1]] + alpha[0][i-1]*Tp['Sunny']['Rainy']*Ep['Sunny'][observations[i-1]]

alpha

array([[1.      , 0.21    , 0.0462  , 0.021294],
       [0.      , 0.09    , 0.0378  , 0.010206]])

In [4]:
#BACKWARD PROCEDURE

beta = np.zeros((len(Tp), len(observations)+1))
beta[:,len(observations)] = [1,1]

for i in range(len(observations)-1, -1, -1):
  beta[0][i] = beta[0][i+1]*Tp['Sunny']['Sunny']*Ep['Sunny'][observations[i]] + beta[1][i+1]*Tp['Sunny']['Rainy']*Ep['Sunny'][observations[i]]
  beta[1][i] = beta[1][i+1]*Tp['Rainy']['Rainy']*Ep['Rainy'][observations[i]] + beta[0][i+1]*Tp['Rainy']['Sunny']*Ep['Rainy'][observations[i]]

beta

array([[0.0315, 0.045 , 0.6   , 1.    ],
       [0.029 , 0.245 , 0.1   , 1.    ]])

In [10]:
gamma = (alpha * beta) / np.sum(alpha * beta, axis=0)
best_states = np.argmax(gamma, axis=0)

print("Gamma values:")
print(gamma)
print("Best states:")
print(best_states)
print()
print("Best Sequence is : ")
print()
for i in best_states:
    if i == 1 :
        print("Rainy")
    elif i == 0 :
        print("Sunny")


Gamma values:
[[1.    0.3   0.88  0.676]
 [0.    0.7   0.12  0.324]]
Best states:
[0 1 0 0]

Best Sequence is : 

Sunny
Rainy
Sunny
Sunny


In [9]:
#VITERBI

delta = np.zeros((len(Tp), len(observations)+1))
delta[:,0] = Initial_prob
Best_state1 = []

for i in range(1, len(observations)+1):

  s_s = delta[0][i-1]*Tp['Sunny']['Sunny']*Ep['Sunny'][observations[i-1]]
  r_s = delta[1][i-1]*Tp['Rainy']['Sunny']*Ep['Rainy'][observations[i-1]]
  delta[0][i] = max(s_s , r_s)

  r_r = delta[1][i-1]*Tp['Rainy']['Rainy']*Ep['Rainy'][observations[i-1]]
  s_r = delta[0][i-1]*Tp['Sunny']['Rainy']*Ep['Sunny'][observations[i-1]]
  delta[1][i] = max(r_r , s_r)

  Best_state1.append("Sunny" if delta[0][i] >= delta[1][i] else "Rainy")

print(delta)
Best_state1

[[1.      0.21    0.0315  0.01323]
 [0.      0.09    0.0315  0.00567]]


['Sunny', 'Sunny', 'Sunny']