In [7]:
import nltk
import pandas as pd

In [4]:
data = []
with open('MT Eng Tam Dataset.txt', 'r', encoding='utf-8') as f:
    for line in f:
        data.append(line)  # strip() removes leading/trailing whitespace, including newlines

source = []
target = []
for line in data:
    line = line.split("        ")
    source.append(line[0])
    target.append(line[1])
print(source)

['\ufeffI slept.', 'Calm down.', "I'll walk.", 'Who is he?', 'Who knows?', 'Definitely!', 'She smiled.', 'Talk to me!', 'Who is she?', 'Go to sleep.', 'It may rain.', 'She bit him.', 'She hit him.', 'She is kind.', 'She is eight.', 'Where are we?', 'Keep in touch!', 'See you again.', 'Give it to her.', 'I ate too much.', "I'll see to it.", "It's up to you.", 'Leave it to me.', 'Listen to this!', "That's the way.", 'Come and see me.', "Don't lie to me.", 'He began to run.', 'He just arrived.', 'He likes to run.', 'How is your dad?', 'I want to sleep.', "I'm able to run.", 'Raise your hand.', 'What did he say?', 'When can we eat?', 'Come and help us.', 'He is still here.', 'I have to go now.', 'I know that much.', 'I made a mistake.', 'I walk to school.', "That's our house.", 'Those are my CDs.', 'Walk ahead of me.', "We'll follow you.", 'Beware of the dog!', 'He came back soon.', 'He has three sons.', 'I know how to ski.', 'I know what to do.', "I'm kind of happy.", 'Keep to the right.'

In [5]:
print(target)

['நான் தூங்கினேன்.', 'அமைதியாக இருங்கள்', 'நான் நடப்பேன்.', 'அவன் யார்?', 'யாருக்குத் தெரியும்?', 'நிச்சயமாக', 'அவள் சிரித்தாள்', 'என்னிடம் பேசு', 'அவள் யார்?', 'போய் தூங்கு', 'மழை பெய்யலாம்', 'அவள் அவனைக் கடித்தாள்', 'அவள் அவனைக் அடித்தாள்', 'அவள் அன்பானவள்', 'அவளுக்கு எட்டு வயது', 'நாம் எங்கே இருக்கிறோம்?', 'தொடர்பில் இரு', 'மறுபடியும் சந்திப்போம்', 'அவளிடம் கொடு', 'நான் நிறைய சாப்பிட்டேன்', 'அதை நான் பார்க்கிறேன்', 'உன் கையில்தான் இருக்கிறது', 'என்னிடம் விட்டுவிடு', 'இதைக் கேள்', 'அந்த பக்கம்தான் வழி', 'என்னை வந்து பார்', 'என்னிடம் பொய் சொல்லாதே', 'அவன் ஓட ஆரம்பித்தான்', 'அவன் இப்பொழுதுதான் வந்தான்', 'அவன் ஓட விருப்பப் படுகிறான்', 'தங்களுடைய தந்தையார் எப்படி இருக்கிறார்கள்?', 'நான் தூங்க விரும்புகிறேன்', 'என்னால் ஓட முடிகிறது', 'கையைத் தூக்கு', 'அவன் என்ன சொன்னான்?', 'எப்பொழுது நம்மால் சாப்பிட முடியும்', 'வா எங்களுக்கு உதவி செய்', 'அவன் இன்னும் இருக்கிறான்', 'நான் இப்பொழுது போக வேண்டும்', 'எனக்கு அவ்வளவு தெரியும்.', 'நான் ஒரு தவறு செய்தேன்?', 'நான் பள்ளிக்கு நடந்து செல்கிறேன்', 'அது

In [8]:
df = pd.DataFrame({"English":source,"Tamil":target})
df.head()

English                 Tamil
0   I slept.      நான் தூங்கினேன்.
1  Calm down.     அமைதியாக இருங்கள்
2  I'll walk.        நான் நடப்பேன்.
3  Who is he?            அவன் யார்?
4  Who knows?  யாருக்குத் தெரியும்?

In [9]:
source_vocab = set(''.join(source))
target_vocab = set(''.join(target))
print(source_vocab)

{'m', 'x', 'e', 'h', 'G', 'F', 'p', 'r', '0', 'S', 'd', 'C', '2', '.', 'k', 'y', 'L', 'j', '?', 'u', 'K', 'H', 'P', 'T', 'c', 'W', 'D', '!', 's', 'o', 'i', 'l', "'", 'v', 'z', 'Y', 'M', 'N', 'f', 't', 'w', 'a', 'b', 'g', 'R', 'B', 'A', 'J', 'q', '\ufeff', 'n', ' ', ',', 'I'}


In [10]:
print(target_vocab)

{'ஜ', '்', 'ல', 'ா', 'ூ', 'ட', ',', 'ய', 'க', 'ஆ', 'ச', 'ொ', '0', 'ெ', 'ன', 'C', 'ஓ', 'ஸ', '2', 'ஷ', '.', 'ஒ', 'ங', '?', 'ஞ', 'த', 'ே', 'ண', 'D', 'ோ', '!', 'அ', '(', 'ள', 'ந', 'ம', 'ஊ', 'ஏ', 'ர', 'ீ', 'ி', 'இ', 'ு', 'வ', 'எ', 'ப', 'உ', 'ை', ' ', 'ற', ')', 'ழ'}


In [11]:
source_vocab_len = len(source_vocab)
target_vocab_len = len(target_vocab)

In [12]:
print(source_vocab_len)
print(target_vocab_len)

54
52


In [38]:
source_char_int = {char:int for int,char in enumerate(source_vocab)}
target_char_int = {char:int for int,char in enumerate(target_vocab)}
source_int_char = {int: char for char,int in source_char_int.items()}
target_int_char = {int: char for char,int in target_char_int.items()}

print(source_char_int)
print(target_char_int)

{'m': 0, 'x': 1, 'e': 2, 'h': 3, 'G': 4, 'F': 5, 'p': 6, 'r': 7, '0': 8, 'S': 9, 'd': 10, 'C': 11, '2': 12, '.': 13, 'k': 14, 'y': 15, 'L': 16, 'j': 17, '?': 18, 'u': 19, 'K': 20, 'H': 21, 'P': 22, 'T': 23, 'c': 24, 'W': 25, 'D': 26, '!': 27, 's': 28, 'o': 29, 'i': 30, 'l': 31, "'": 32, 'v': 33, 'z': 34, 'Y': 35, 'M': 36, 'N': 37, 'f': 38, 't': 39, 'w': 40, 'a': 41, 'b': 42, 'g': 43, 'R': 44, 'B': 45, 'A': 46, 'J': 47, 'q': 48, '\ufeff': 49, 'n': 50, ' ': 51, ',': 52, 'I': 53}
{'ஜ': 0, '்': 1, 'ல': 2, 'ா': 3, 'ூ': 4, 'ட': 5, ',': 6, 'ய': 7, 'க': 8, 'ஆ': 9, 'ச': 10, 'ொ': 11, '0': 12, 'ெ': 13, 'ன': 14, 'C': 15, 'ஓ': 16, 'ஸ': 17, '2': 18, 'ஷ': 19, '.': 20, 'ஒ': 21, 'ங': 22, '?': 23, 'ஞ': 24, 'த': 25, 'ே': 26, 'ண': 27, 'D': 28, 'ோ': 29, '!': 30, 'அ': 31, '(': 32, 'ள': 33, 'ந': 34, 'ம': 35, 'ஊ': 36, 'ஏ': 37, 'ர': 38, 'ீ': 39, 'ி': 40, 'இ': 41, 'ு': 42, 'வ': 43, 'எ': 44, 'ப': 45, 'உ': 46, 'ை': 47, ' ': 48, 'ற': 49, ')': 50, 'ழ': 51}


In [39]:
print(target_int_char)

{0: 'ஜ', 1: '்', 2: 'ல', 3: 'ா', 4: 'ூ', 5: 'ட', 6: ',', 7: 'ய', 8: 'க', 9: 'ஆ', 10: 'ச', 11: 'ொ', 12: '0', 13: 'ெ', 14: 'ன', 15: 'C', 16: 'ஓ', 17: 'ஸ', 18: '2', 19: 'ஷ', 20: '.', 21: 'ஒ', 22: 'ங', 23: '?', 24: 'ஞ', 25: 'த', 26: 'ே', 27: 'ண', 28: 'D', 29: 'ோ', 30: '!', 31: 'அ', 32: '(', 33: 'ள', 34: 'ந', 35: 'ம', 36: 'ஊ', 37: 'ஏ', 38: 'ர', 39: 'ீ', 40: 'ி', 41: 'இ', 42: 'ு', 43: 'வ', 44: 'எ', 45: 'ப', 46: 'உ', 47: 'ை', 48: ' ', 49: 'ற', 50: ')', 51: 'ழ'}


In [15]:
source_sequence = []
target_sequence = []
for text in source:
    seq = [source_char_int[char] for char in text]
    source_sequence.append(seq)
for text in target:
    seq = [target_char_int[char] for char in text]
    target_sequence.append(seq)


In [16]:
print(source_sequence)
print(target_sequence)

[[49, 53, 51, 28, 31, 2, 6, 39, 13], [11, 41, 31, 0, 51, 10, 29, 40, 50, 13], [53, 32, 31, 31, 51, 40, 41, 31, 14, 13], [25, 3, 29, 51, 30, 28, 51, 3, 2, 18], [25, 3, 29, 51, 14, 50, 29, 40, 28, 18], [26, 2, 38, 30, 50, 30, 39, 2, 31, 15, 27], [9, 3, 2, 51, 28, 0, 30, 31, 2, 10, 13], [23, 41, 31, 14, 51, 39, 29, 51, 0, 2, 27], [25, 3, 29, 51, 30, 28, 51, 28, 3, 2, 18], [4, 29, 51, 39, 29, 51, 28, 31, 2, 2, 6, 13], [53, 39, 51, 0, 41, 15, 51, 7, 41, 30, 50, 13], [9, 3, 2, 51, 42, 30, 39, 51, 3, 30, 0, 13], [9, 3, 2, 51, 3, 30, 39, 51, 3, 30, 0, 13], [9, 3, 2, 51, 30, 28, 51, 14, 30, 50, 10, 13], [9, 3, 2, 51, 30, 28, 51, 2, 30, 43, 3, 39, 13], [25, 3, 2, 7, 2, 51, 41, 7, 2, 51, 40, 2, 18], [20, 2, 2, 6, 51, 30, 50, 51, 39, 29, 19, 24, 3, 27], [9, 2, 2, 51, 15, 29, 19, 51, 41, 43, 41, 30, 50, 13], [4, 30, 33, 2, 51, 30, 39, 51, 39, 29, 51, 3, 2, 7, 13], [53, 51, 41, 39, 2, 51, 39, 29, 29, 51, 0, 19, 24, 3, 13], [53, 32, 31, 31, 51, 28, 2, 2, 51, 39, 29, 51, 30, 39, 13], [53, 39, 32, 28, 

In [17]:
max_seq_length = max(max(len(seq) for seq in source_sequence),max(len(seq) for seq in target_sequence))
max_seq_length
import tensorflow as tf

In [18]:
source_sequence = tf.keras.preprocessing.sequence.pad_sequences(source_sequence,max_seq_length,padding='post')
target_sequence = tf.keras.preprocessing.sequence.pad_sequences(target_sequence,max_seq_length,padding='post')

In [19]:
print(source_sequence)

[[49 53 51 ...  0  0  0]
 [11 41 31 ...  0  0  0]
 [53 32 31 ...  0  0  0]
 ...
 [53 39 32 ...  0  0  0]
 [53 38 51 ...  0  0  0]
 [53 39 32 ...  0  0  0]]


In [20]:
print(target_sequence)

[[34  3 14 ...  0  0  0]
 [31 35 47 ...  0  0  0]
 [34  3 14 ...  0  0  0]
 ...
 [21 38 42 ...  0  0  0]
 [46 22  1 ...  0  0  0]
 [44 14  1 ...  1  2 47]]


In [21]:
import numpy as np
model = tf.keras.models.Sequential([
    tf.keras.layers.Embedding(source_vocab_len,64,input_length=max_seq_length),
    tf.keras.layers.SimpleRNN(128,return_sequences=True),
    tf.keras.layers.Dense(target_vocab_len,activation='softmax')
])
model.compile(optimizer='adam',loss= 'categorical_crossentropy',metrics=['accuracy'])


In [22]:
target_seq_onehot = np.array([tf.keras.utils.to_categorical(seq,target_vocab_len) for seq in target_sequence])

In [48]:
model.fit(
    source_sequence,
    target_seq_onehot,
    epochs = 1000,
    batch_size = 4,
    verbose = 1
)

Epoch 1/1000
52/52 [==============================] - 1s 21ms/step - loss: 0.9571 - accuracy: 0.7526
Epoch 2/1000
52/52 [==============================] - 1s 20ms/step - loss: 0.9588 - accuracy: 0.7522
Epoch 3/1000
52/52 [==============================] - 1s 21ms/step - loss: 0.9621 - accuracy: 0.7533
Epoch 4/1000
52/52 [==============================] - 1s 20ms/step - loss: 0.9530 - accuracy: 0.7544
Epoch 5/1000
52/52 [==============================] - 1s 22ms/step - loss: 0.9525 - accuracy: 0.7543
Epoch 6/1000
52/52 [==============================] - 1s 21ms/step - loss: 0.9630 - accuracy: 0.7534
Epoch 7/1000
52/52 [==============================] - 1s 21ms/step - loss: 0.9468 - accuracy: 0.7554
Epoch 8/1000
52/52 [==============================] - 1s 24ms/step - loss: 0.9492 - accuracy: 0.7552
Epoch 9/1000
52/52 [==============================] - 1s 21ms/step - loss: 0.9411 - accuracy: 0.7566
Epoch 10/1000
52/52 [==============================] - 1s 22ms/step - loss: 0.9537 - accura

In [49]:
def translate(text):
    input_seq = [source_char_int[char] for char in text if char in source_char_int]
    input_seq = tf.keras.preprocessing.sequence.pad_sequences([input_seq],maxlen = max_seq_length,padding='post')
    output_sequence = model.predict(input_seq)[0]
    output = ''
    for char_prob in output_sequence:
        char_idx = np.argmax(char_prob)
        char = target_int_char[char_idx]
        output += char
    return output

In [50]:
s = "Hi how are you"
print(translate(s))

1/1 [==============================] - 0s 172ms/step
அான் ்டைகவறன்க விரமகுகி்ஜய்ஜஜஜஜஜஜஜஜஜஜஜஜஜஜஜஜஜஜஜஜஜஜஜஜஜஜஜஜஜஜஜஜஜஜஜஜஜஜஜஜஜஜஜஜஜஜஜஜஜஜஜஜஜஜஜஜஜஜஜஜஜஜஜஜஜஜஜஜஜஜஜஜஜஜஜஜஜஜஜஜஜஜ


In [43]:
target_int_char

{0: 'ஜ',
 1: '்',
 2: 'ல',
 3: 'ா',
 4: 'ூ',
 5: 'ட',
 6: ',',
 7: 'ய',
 8: 'க',
 9: 'ஆ',
 10: 'ச',
 11: 'ொ',
 12: '0',
 13: 'ெ',
 14: 'ன',
 15: 'C',
 16: 'ஓ',
 17: 'ஸ',
 18: '2',
 19: 'ஷ',
 20: '.',
 21: 'ஒ',
 22: 'ங',
 23: '?',
 24: 'ஞ',
 25: 'த',
 26: 'ே',
 27: 'ண',
 28: 'D',
 29: 'ோ',
 30: '!',
 31: 'அ',
 32: '(',
 33: 'ள',
 34: 'ந',
 35: 'ம',
 36: 'ஊ',
 37: 'ஏ',
 38: 'ர',
 39: 'ீ',
 40: 'ி',
 41: 'இ',
 42: 'ு',
 43: 'வ',
 44: 'எ',
 45: 'ப',
 46: 'உ',
 47: 'ை',
 48: ' ',
 49: 'ற',
 50: ')',
 51: 'ழ'}